// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlu2CR5cnLx8YGwgVjQ0PYhRTzlImF-ys',
    appId: '1:707676750171:web:ce8a90b4568b3ebea69a7e',
    messagingSenderId: '707676750171',
    projectId: 'patriots-parking',
    authDomain: 'patriots-parking.firebaseapp.com',
    storageBucket: 'patriots-parking.appspot.com',
    measurementId: 'G-WJNFSVGYX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKJylxouNrYDsESQLab-HL4dInksvhwk',
    appId: '1:707676750171:android:7578cc5f35e2020ea69a7e',
    messagingSenderId: '707676750171',
    projectId: 'patriots-parking',
    storageBucket: 'patriots-parking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3oGGucWXbwSPVetra158_JsiUAx3XlZM',
    appId: '1:707676750171:ios:cfceb11eac828315a69a7e',
    messagingSenderId: '707676750171',
    projectId: 'patriots-parking',
    storageBucket: 'patriots-parking.appspot.com',
    iosClientId: '707676750171-354rd2pn7rta4amthla5hk62cratf601.apps.googleusercontent.com',
    iosBundleId: 'com.example.patriotsParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3oGGucWXbwSPVetra158_JsiUAx3XlZM',
    appId: '1:707676750171:ios:cfceb11eac828315a69a7e',
    messagingSenderId: '707676750171',
    projectId: 'patriots-parking',
    storageBucket: 'patriots-parking.appspot.com',
    iosClientId: '707676750171-354rd2pn7rta4amthla5hk62cratf601.apps.googleusercontent.com',
    iosBundleId: 'com.example.patriotsParking',
  );
}
